name: weather
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  intl: ^0.18.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  http: ^0.13.5
  get: ^4.6.5
  sleek_circular_slider: ^2.0.1
  timezone: ^0.9.2
  pull_down_button: ^0.9.1
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: RussoOne
      fonts:
        - asset: assets/fonts/RussoOne-Regular.ttf
